### ISSUE TITLE
Missing css documentation for best_in_place.purr.js

### ISSUE THREAD

**Issue by josefsj3m** [bernat/best_in_place#524]
I tried to use best in place notification on error, but the message was not displayed by jquery.purr. Checking the code I saw that best_in_place.purr.js uses a css class .bip-flash-error. Everything works ok when I provided this class.

I have not seen the reference to this class in documentation. I use the following as an example:

```css
.bip-flash-error {
  position: fixed;
  top: 30px;
  right: 100px;
  width: 250px;
  padding: 20px;
  background-color: #FCC;
  border: solid 2px #C66;
  &:first-letter { text-transform: uppercase; }
}
```

José Fernando
